### ISSUE TITLE
Server would not start

### ISSUE THREAD

**Issue by B-Keshav** [learn-co-curriculum/react-hooks-state-arrays#12]
### Canvas Link

https://learning.flatironschool.com/courses/5235/assignments/210446?module_item_id=485168

### Concern

Cloned the git hub repo locally to try and code along but when I ran "npm install && npm start" the server did not start properly and gave me the same error every time I tried to start it:

Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'

**Comment by jlboba** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

`chokidar` is not a dependency required for this repository, so unfortunately it might just be an `npm` version issue or something else with your environment. Installing `chokidar` manually as npm suggests may fix the issue.

Thank you for bringing this up, however! We will keep it in mind if it continues occuring for students in the future.

**Comment by alandio** [comment]
I'm currently having a similar issue. Please let me know if there is any other details required

Steps to reproduce:
1. clone the repo
2. run `npm install`
3. run `npm run`

node version:  v16.18.1
npm version: 8.19.2


<details>
<summary>Logs</summary>

```bash
Compiled with warnings.

src/components/SpicyFoodList.js
  Line 5:17:  'setFoods' is assigned a value but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

/home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js:17
throw new Error(
^

Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'
Require stack:
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/DirectoryWatcher.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/watcherManager.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/watchpack.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/webpack/lib/webpack.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/react-scripts/scripts/start.js
chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
Require stack:
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/DirectoryWatcher.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/watcherManager.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/watchpack.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/webpack/lib/webpack.js
- /home/vscode/assignments/react-hooks-state-arrays/node_modules/react-scripts/scripts/start.js

    at Object.<anonymous> (/home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js:17:7)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/vscode/assignments/react-hooks-state-arrays/node_modules/watchpack/lib/DirectoryWatcher.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
```

</details>

**Comment by alandio** [comment]
I tried to change node version to v18, and run `npm audit fix --force` and it worked :tada:
